version: '3.3'

services:
    php:
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/html
    nginx:
        volumes:
            - ${SYMFONY_APP_PATH}public/:/var/www/html
        ports:
            - ${NGINX_HOST_PORT}:80
    composer:
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/html
    nodejs:
        volumes:
            - ${SYMFONY_APP_PATH}:/home/node/app
        expose:
            - 8083