version: '3.3'

services:
    composer:
        image: composer
        working_dir: /app
        command: composer require symfony/event-dispatcher
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/html